# Generated by Django 4.2.6 on 2023-11-04 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0002_book_context'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='context',
            field=models.TextField(max_length=100),
        ),
    ]
